version: '2.2'
networks:
  isolation-network:
    driver: bridge
services:
    accounting:
        container_name: accounting
        restart: always
        build:
            context: ./accounting
        ports:
            - "5002:5002"
        networks:
            - isolation-network

    sales:
        container_name: sales
        restart: always
        build:
            context: ./sales
        ports:
            - "5001:5001"
        networks:
            - isolation-network
    warehouse:
        container_name: warehouse
        restart: always
        build:
            context: ./warehouse
        ports:
            - "5003:5003"
        networks:
            - isolation-network
    api:
        container_name: api
        restart: always
        build:
            context: ./api
        ports:
            - "5000:5000"
        networks:
            - isolation-network
    nginx:
        container_name: nginx
        depends_on:
            - api
        restart: always
        build: 
            context: ./nginx
        networks:
            - isolation-network
        expose:
            - "8080"
        ports:
            - "80:8080"
